In [1]:
# Question 1

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

a_vertical = np.vstack((a, b))
b_horizontal = np.hstack((a, b))

print(a_vertical)
print(b_horizontal)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:
# Question 2

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

common_items = np.intersect1d(a,b)

print(common_items)

[5]


In [3]:
# Question 3

a = np.array([1,2,3,4,5])

extracted = np.where(a > 4)

print(extracted)



(array([4]),)


In [4]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered)

<class 'FileNotFoundError'>: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data not found.

In [ ]:
# Pandas Question 1

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

result = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

In [7]:
# Pandas Question 2

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

print(df)

result = df[df.sum(axis=1) > 100]

print(result)

     0   1   2   3
0   38  16  30  33
1   36  24  11  25
2   29  23  37  33
3   14  13  20  10
4   29  39  20  37
5   14  31  26  24
6   34  18  31  20
7   13  30  21  21
8   30  19  13  21
9   35  14  26  23
10  33  32  28  22
11  33  20  29  17
12  21  18  29  18
13  32  15  11  24
14  31  19  35  23
     0   1   2   3
0   38  16  30  33
2   29  23  37  33
4   29  39  20  37
6   34  18  31  20
10  33  32  28  22
14  31  19  35  23
